meta_product_name: "Sickbeans"
meta_title: "Sickbeans - Soybeans with selected diseases, injuries, and traits will be removed from sample."
meta_description: "Play with a sample size of 307 soybeans by selecting diseases, injuries to remove from the sample."
meta_image: "cover.png"
twitter_account: "@tristanviney"
